name: merge

on:
  workflow_dispatch:
    inputs:
      params_json:
        description: 'JSON string of parameters'
        required: true
        default: '{}'

env:
  # Google sheet secrets
  credentials_json_string: ${{ secrets.CREDENTIALS_JSON }}
  sheet_id: ${{ secrets.SHEET_ID }}

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Parse JSON input
        id: parse_json
        run: |
          echo "Parsing JSON input..."
          echo '${{ github.event.inputs.params_json }}' | jq '.' > input_params.json

      - name: Set environment variables from JSON input
        id: set_env
        run: |
          echo "Setting environment variables..."
          cat input_params.json
          for key in $(jq -r 'keys[]' input_params.json); do
            value=$(jq -r --arg key "$key" '.[$key]' input_params.json)
            echo "Setting $key=$value"
            echo "$key=$value" >> $GITHUB_ENV
          done

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ runner.tool_cache }}/python
          key: ubuntu-latest-python-${{ hashFiles('requirements.txt') }}-basic

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 

      - name: running merge
        run: |
          python merge.py